version: '3'

services:
  spring-boot:
    image: fendijatmiko/springboot
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8080
    volumes:
      - /data/spring-boot-app
